### ISSUE TITLE
Question regarding Async Example

### ISSUE THREAD

**Issue by rusco** [yallajs/yalla#8]
Hi, 
I have a question regarding the Async Example at codepen:

https://codepen.io/yallajs/pen/XzKqBb

Isn't the  inner resolve statment 
```html
<div>This is printed after 1s</div><button onclick="${e => update()}">Try again</button>
```
supposed to disappear after each click of the "Update" Button for one second ? 
At least this is my interpretation of the code. 

What I see in my evergreen Chrome Browser is that the text does not disappear. 
In addition to that the first rendering shows a shadowed Button with the label "outlet". 

Could you comment on that ? 
Thank you !

**Comment by yallajs** [comment]
Hi, when I wrote the example with that version of yalla it was disappearing. Then it turns out it cause a lot of issue, for example the screen is flickering whenever yalla perform update and hits async code. 

So we decided to fix the issue by not destroying the previous created node and update the node once we receive the new data. And it turns out it feels more natural because when we say async it doesn't mean we want to update immediately, inatead we want to update when we received the new value.

Regarding the outlet remarks it's actually running on debug mode. We will disable this features in next version. Sorry for the inconvenience
