### ISSUE TITLE
SVG with Yalla

### ISSUE THREAD

**Issue by rusco** [yallajs/yalla#9]
I tried to play with SVG and made this Pen:

https://codepen.io/anon/pen/OOEpwy

I see some warnings on the Firefox 57 console (also Chrome shows some similar warnings):
Valor no esperado  al interpretar el atributo cx. yalla.js: 552:16
Valor no esperado  al interpretar el atributo cy.yalla.js: 552:16
El uso de nodeValue en atributos está desaprobado. Use en su lugar value. yalla.js:467:32

In english it means sth. like:
Not expecting value  interpretating the cx attribute
The use of nodeValue on attributes is deprecated. Use value instead. 

Have you already tried creating SVG's ?  Are you using a deprecated API ?
Thanks for looking into this

**Comment by yallajs** [comment]
Hello,

The issue is because the cx and cy expecting number, while during the parsing yalla put a comment node into that attribute, nothing was broken its just error message will comeup in the console. This can be easily fix by using `.bind`. 

So here's the fix code

```javascript
const circle = html`
<svg height="100" width="100">
     <circle cx.bind="${x}" cy.bind="${y}" r="40" stroke="black" stroke-width="${stroke}" fill="${color}" /> 
</svg>`;
```

**Comment by rusco** [comment]
I got stuck again, your help is very appreciated !

Why does circle2 not getting rendered, at least I can see the dom updates in the Developer tools, it just remains invisible ?

https://codepen.io/anon/pen/QOxqwM

The "bind" function you mentioned, where is it implemented, inside Yalla ?

**Comment by yallajs** [comment]
The `.bind` is inside Yalla. 

SVG is very strict with the node attribute width and height should be numeric. Since yalla marked the dynamic part with comment node, browser will throw error in devtools when yalla walked the SVG attribute for the first time. That is why we introduce `.bind` to avoid this error message.

Regarding the htmlCollection for SVG, based on the codepen link it seems its a valid bug. We have identify the issue, we will fix it in next release.

Thank you

**Comment by yallajs** [comment]
Hi Rusco,

We have fixed the issue in latest release please check your codepen link again. Thank you 
https://codepen.io/anon/pen/QOxqwM
